<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>1.0.1</Version>

        <IsPackable>true</IsPackable>

        <Description>MySQL provider integration for Raycynix.Extensions.Database with AddMySql registration, MySQL connection-string composition, and EF Core UseMySQL configuration.</Description>
        <PackageTags>raycynix;database;mysql;provider;efcore;entityframework;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.6"/>
        <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.6"/>
        <PackageReference Include="System.Security.Permissions" Version="10.0.6"/>
        <PackageReference Include="ZstdSharp.Port" Version="0.8.7"/>
        <PackageReference Include="Google.Protobuf" Version="3.34.1"/>
        <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Database\Raycynix.Extensions.Database.csproj"/>
    </ItemGroup>

</Project>
