<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>1.0.2</Version>

        <IsPackable>true</IsPackable>
        <PackageReleaseNotes>Added a host-agnostic Security example focused on SecurityConfiguration binding and core service registration.</PackageReleaseNotes>

        <Description>Core security services, typed security configuration, shared identity context handling, and application-level authorization composition for Raycynix applications.</Description>
        <PackageTags>raycynix;security;authorization;identity;claims;jwt;configuration;rbac;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Raycynix.Extensions.Security.Abstractions\Raycynix.Extensions.Security.Abstractions.csproj" />
      <ProjectReference Include="..\Raycynix.Extensions.Configuration\Raycynix.Extensions.Configuration.csproj" />
    </ItemGroup>

</Project>
