<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Version>2.1.0</Version>

        <IsPackable>true</IsPackable>
        <PackageReleaseNotes>Initial 2.1.0 Elasticsearch logging integration package. Adds AddElastic() for Raycynix logging, binds LoggingConfiguration:ElasticConfiguration, and configures the Serilog Elasticsearch sink.</PackageReleaseNotes>

        <Description>Elasticsearch sink integration for Raycynix Serilog-based logging.</Description>
        <PackageTags>raycynix;logging;serilog;elasticsearch;elastic;structured-logging;sink;integration;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Raycynix.Extensions.Logging\Raycynix.Extensions.Logging.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Elastic.Channels" Version="0.43.0" />
        <PackageReference Include="Elastic.Ingest.Elasticsearch" Version="0.43.0" />
        <PackageReference Include="Elastic.Serilog.Sinks" Version="9.0.0" />
        <PackageReference Include="Elastic.Transport" Version="0.17.1" />
    </ItemGroup>

</Project>
