<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.1.1</Version>

        <IsPackable>true</IsPackable>
        
        <Description>Centralized metrics module.</Description>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Raycynix.Extensions.Metrics.Abstractions\Raycynix.Extensions.Metrics.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
      <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.3" />
      <PackageReference Include="prometheus-net" Version="8.2.1" />
      <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
      <PackageReference Include="prometheus-net.AspNetCore.HealthChecks" Version="8.2.1" />
    </ItemGroup>

</Project>
