<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.1.2</Version>

        <IsPackable>true</IsPackable>

        <Description>Core secret resolution services, secret provider composition, and environment-aware secret access for Raycynix applications.</Description>
        <PackageTags>raycynix;secrets;configuration;environment;providers;secret-management;github;teamcity;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Raycynix.Extensions.Security.Abstractions\Raycynix.Extensions.Security.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    </ItemGroup>

</Project>
