<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>1.0.0</Version>

        <IsPackable>true</IsPackable>

        <Description>Abstractions and contracts for Raycynix exception handling, retry execution, masking, and background failure flows.</Description>
        <PackageTags>raycynix;exceptions;abstractions;contracts;error-handling;retry;masking;background;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

</Project>
