<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>1.0.0</Version>

        <IsPackable>true</IsPackable>

        <Description>ASP.NET Core middleware and endpoint integration for Raycynix metrics exposure, HTTP request instrumentation, and Prometheus scraping.</Description>
        <PackageTags>raycynix;metrics;aspnetcore;middleware;endpoints;prometheus;http;instrumentation;scraping;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Metrics\Raycynix.Extensions.Metrics.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
    </ItemGroup>

</Project>
