<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.7.0</Version>

        <IsPackable>true</IsPackable>

        <Description>Transport-agnostic messaging contracts, codecs, publishers, and handlers for Raycynix applications.</Description>
        <PackageTags>raycynix;messaging;abstractions;events;integration;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Contracts\Raycynix.Extensions.Contracts.csproj" />
        <ProjectReference Include="..\Raycynix.Extensions.Security.Abstractions\Raycynix.Extensions.Security.Abstractions.csproj" />
    </ItemGroup>

</Project>
