<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <Product>Raycynix.Extensions.Core</Product>
        <RootNamespace>Raycynix.Extensions.Core</RootNamespace>
        <AssemblyName>Raycynix.Extensions.Core</AssemblyName>
        <PackageId>Raycynix.Extensions.Core</PackageId>

        <!--<PackageIcon>logo.png</PackageIcon>-->

        <Description>Core abstractions, Result model, and common helpers for microservice architecture.</Description>
        <Version>0.1.1</Version>
        <Authors>Raycynix</Authors>
        <Company>Raycynix</Company>
        <Copyright>Raycynix</Copyright>

        <RepositoryUrl>https://github.com/Raycynix/Extensions</RepositoryUrl>
        <RepositoryType>GitHub</RepositoryType>

        <PackageProjectUrl>https://github.com/Raycynix/Extensions</PackageProjectUrl>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageTags>core;extensions;microservices;shared;raycynix</PackageTags>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <WarningsAsErrors>CS1591</WarningsAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <IsPackable>true</IsPackable>

        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="logo.png" Pack="true" Visible="false"/>
        <None Include="LICENSE" Pack="true" Visible="false"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
    </ItemGroup>

</Project>