<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.2.1</Version>

        <IsPackable>true</IsPackable>

        <Description>Core tracing services for Raycynix applications.</Description>
        <PackageTags>raycynix;tracing;diagnostics;activitysource;observability;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Common\Raycynix.Extensions.Common.csproj"/>
        <ProjectReference Include="..\Raycynix.Extensions.Logging\Raycynix.Extensions.Logging.csproj"/>
        <ProjectReference Include="..\Raycynix.Extensions.Tracing.Abstractions\Raycynix.Extensions.Tracing.Abstractions.csproj"/>
    </ItemGroup>
</Project>
