<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.2.1</Version>

        <IsPackable>true</IsPackable>

        <Description>Shared API contracts, versioning primitives, paging models, and transport-safe error shapes for .NET applications.</Description>
        <PackageTags>raycynix;contracts;dto;versioning;api;errors;paging;aspnet;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

</Project>
