<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>1.0.1</Version>

        <IsPackable>true</IsPackable>

        <Description>ASP.NET Core integration for Raycynix observability, including correlation middleware, endpoint mapping, and outgoing HTTP correlation propagation.</Description>
        <PackageTags>raycynix;observability;aspnetcore;middleware;endpoints;http;correlation;propagation;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Observability\Raycynix.Extensions.Observability.csproj" />
        <ProjectReference Include="..\Raycynix.Extensions.Tracing.AspNetCore\Raycynix.Extensions.Tracing.AspNetCore.csproj" />
        <ProjectReference Include="..\Raycynix.Extensions.Metrics.AspNetCore\Raycynix.Extensions.Metrics.AspNetCore.csproj" />
        <ProjectReference Include="..\Raycynix.Extensions.Security.Abstractions\Raycynix.Extensions.Security.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
