<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.2.1</Version>

        <IsPackable>true</IsPackable>
        
        <Description>Abstractions and contracts for Raycynix tracing services, activity sources, and shared tracing primitives.</Description>
        <PackageTags>raycynix;tracing;abstractions;contracts;diagnostics;activitysource;primitives;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

</Project>
