<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.1.1</Version>

        <IsPackable>true</IsPackable>
        
        <Description>Centralized abstractions for tracing module.</Description>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

</Project>
