<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.1.0</Version>

        <IsPackable>true</IsPackable>

        <Description>Centralized abstractions for Exceptions module.</Description>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Raycynix.Extensions.Exceptions.Abstractions\Raycynix.Extensions.Exceptions.Abstractions.csproj" />
    </ItemGroup>

</Project>
