<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.1.0</Version>

        <IsPackable>true</IsPackable>

        <Description>Centralized abstractions for Exceptions module.</Description>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Raycynix.Extensions.Exceptions.Abstractions\Raycynix.Extensions.Exceptions.Abstractions.csproj" />
      <ProjectReference Include="..\Raycynix.Extensions.Logging.Abstractions\Raycynix.Extensions.Logging.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
      <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.9" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
    </ItemGroup>

</Project>
