<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	  <LangVersion>latest</LangVersion>
	  <TreatWarningsAsErrors>false</TreatWarningsAsErrors>

	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

	  <IsPackable>true</IsPackable>
	  <PackageId>Raycynix.Extensions.Messaging</PackageId>
	  <Version>0.1.0</Version>
	  <Authors>IruNil</Authors>
	  <Company>Raycynix</Company>
	  <Product>Raycynix.Extensions.Messaging</Product>
	  <Description>Unified message bus for Raycynix microservices supporting RabbitMQ and Kafka.</Description>
	  <RepositoryUrl>https://github.com/Raycynix/Extensions</RepositoryUrl>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <PackageProjectUrl>https://github.com/Raycynix/Extensions</PackageProjectUrl>
	  <!--<PackageIcon>logo.png</PackageIcon>-->
	  <PackageTags>raycynix;messaging;rabbitmq;kafka;microservices</PackageTags>

	  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	  <WarningsAsErrors>CS1591</WarningsAsErrors>

	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

	<ItemGroup>
		<None Include="logo.png" Pack="true" Visible="false" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.12.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

</Project>
