<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <LangVersion>latest</LangVersion>

	  <Product>Raycynix.Extensions.Messaging</Product>
	  <RootNamespace>Raycynix.Extensions.Messaging</RootNamespace>
	  <AssemblyName>Raycynix.Extensions.Messaging</AssemblyName>
	  <PackageId>Raycynix.Extensions.Messaging</PackageId>

	  <!--<PackageIcon>logo.png</PackageIcon>-->

	  <Description>Unified message bus for Raycynix microservices supporting RabbitMQ and Kafka.</Description>
	  <Version>0.1.1</Version>
	  <Authors>Raycynix</Authors>
	  <Company>Raycynix</Company>
	  <Copyright>Raycynix</Copyright>

	  <RepositoryUrl>https://github.com/Raycynix/Extensions</RepositoryUrl>
	  <RepositoryType>GitHub</RepositoryType>

	  <PackageProjectUrl>https://github.com/Raycynix/Extensions</PackageProjectUrl>
	  <PackageLicenseUrl>https://github.com/Raycynix/Extensions/blob/release/LICENSE</PackageLicenseUrl>

	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <PackageTags>raycynix;messaging;rabbitmq;kafkax;extensions</PackageTags>

	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	  <WarningsAsErrors>CS1591</WarningsAsErrors>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>

	  <IsPackable>true</IsPackable>

	  <PublishSingleFile>true</PublishSingleFile>
	  <SelfContained>true</SelfContained>
	  <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

	<ItemGroup>
		<None Include="logo.png" Pack="true" Visible="false" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.12.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

</Project>
