<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>1.0.1</Version>

        <IsPackable>true</IsPackable>

        <Description>ASP.NET Core integration for Raycynix contracts, including endpoint metadata, contract headers, and contract-aware result helpers.</Description>
        <PackageTags>raycynix;contracts;aspnetcore;minimal-api;headers;versioning;http;middleware;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Contracts\Raycynix.Extensions.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
