<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.5.0</Version>
        
        <IsPackable>true</IsPackable>

        <Description>Abstractions for Raycynix database initialization, EF Core model configurators, table-mapping attributes, and model cache contracts.</Description>
        <PackageTags>raycynix;database;abstractions;contracts;efcore;configurators;tablemapping;modelcache;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.5" />
    </ItemGroup>

</Project>
