<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>1.0.1</Version>

        <IsPackable>true</IsPackable>

        <Description>Core observability composition for Raycynix applications, combining logging, metrics, tracing, and ambient operation context registration into a single infrastructure surface.</Description>
        <PackageTags>raycynix;observability;logging;metrics;tracing;correlation;operation-context;composition;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Common\Raycynix.Extensions.Common.csproj"/>
        <ProjectReference Include="..\Raycynix.Extensions.Logging\Raycynix.Extensions.Logging.csproj"/>
        <ProjectReference Include="..\Raycynix.Extensions.Metrics\Raycynix.Extensions.Metrics.csproj"/>
        <ProjectReference Include="..\Raycynix.Extensions.Tracing\Raycynix.Extensions.Tracing.csproj"/>
    </ItemGroup>
</Project>
