<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.4.0</Version>

        <IsPackable>true</IsPackable>

        <Description>Kafka-specific messaging configuration and DI integration for Raycynix applications.</Description>
        <PackageTags>raycynix;messaging;kafka;events;integration;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Confluent.Kafka" Version="2.11.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Messaging\Raycynix.Extensions.Messaging.csproj" />
    </ItemGroup>

</Project>
