<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>1.0.1</Version>

        <IsPackable>true</IsPackable>
        
        <Description>Abstractions and contracts for Raycynix metrics services, counters, gauges, histograms, and shared instrumentation primitives.</Description>
        <PackageTags>raycynix;metrics;abstractions;contracts;counters;gauges;histograms;instrumentation;primitives;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.8" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    </ItemGroup>
    
</Project>
