<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.3.0</Version>

        <IsPackable>true</IsPackable>

        <Description>ASP.NET Core JWT authentication, authorization policies, and shared authorization-attribute integration for Raycynix security.</Description>
        <PackageTags>raycynix;security;aspnetcore;jwt;authentication;authorization;rbac;policies;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Security\Raycynix.Extensions.Security.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    </ItemGroup>

</Project>
