<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.2.1</Version>

        <IsPackable>true</IsPackable>

        <Description>ASP.NET Core startup integration for Raycynix database initialization.</Description>
        <PackageTags>raycynix;database;aspnetcore;web;startup;initialization;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Database.Hosting\Raycynix.Extensions.Database.Hosting.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
