<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.1.1</Version>

        <IsPackable>true</IsPackable>

        <Description>Core typed-configuration registration, defaults, and validation helpers for Raycynix applications.</Description>
        <PackageTags>raycynix;configuration;options;binding;defaults;validation;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Configuration.Abstractions\Raycynix.Extensions.Configuration.Abstractions.csproj" />
    </ItemGroup>

</Project>
