<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.2.2</Version>

        <IsPackable>true</IsPackable>
        
        <Description>Centralized Serilog + Elasticsearch logging module.</Description>
        
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Raycynix.Extensions.Common\Raycynix.Extensions.Common.csproj" />
      <ProjectReference Include="..\Raycynix.Extensions.Logging.Abstractions\Raycynix.Extensions.Logging.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
        <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
        <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Elastic.Serilog.Sinks" Version="9.0.0" />
    </ItemGroup>

</Project>
