<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.1.4</Version>

        <IsPackable>true</IsPackable>

        <Description>Abstractions for Raycynix typed configuration access, defaults, validation, reload governance, change handling, and environments.</Description>
        <PackageTags>raycynix;configuration;abstractions;options;accessor;defaults;validation;environment;reload;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

</Project>
