<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.1.2</Version>

        <IsPackable>true</IsPackable>

        <Description>Abstractions for Raycynix typed configuration defaults, validation, and environments.</Description>
        <PackageTags>raycynix;configuration;abstractions;options;defaults;validation;environment;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

</Project>
